[db]
shadow_port = 54320
port = 54322
major_version = 15

[auth]
site_url = "https://v0-mlodi-jham5541s-projects.vercel.app/"
additional_redirect_urls = ["https://v0-mlodi-jham5541s-projects.vercel.app/", "https://v0-mlodi-jham5541s-projects.vercel.app/**", "https://v0-*-mlodi-jham5541s-projects.vercel.app", "https://v0-*-mlodi-jham5541s-projects.vercel.app/**"]
enable_signup = true

[auth.external.apple]
enabled = true
client_id = "com.mlodi.app"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[studio]
port = 54323

[storage]
file_size_limit = "50MiB"
